[ SMS_Report (TRUE),
  SMS_Group_Name ("CacheInfoEx"),
  SMS_Class_ID ("MICROSOFT|CACHEINFOEX|1.0"),
  Namespace ("root\\\\ccm\\\\SoftMgmtAgent") ]
class CacheInfoEx : SMS_Class_Template
{
    [ SMS_Report (TRUE), key ]
    String     CacheId;
    [ SMS_Report (TRUE) ]
    Boolean     ContentComplete;
    [ SMS_Report (TRUE) ]
    UInt32     ContentFlags;
    [ SMS_Report (TRUE) ]
    String     ContentId;
    [ SMS_Report (TRUE) ]
    UInt32     ContentSize;
    [ SMS_Report (TRUE) ]
    String     ContentType;
    [ SMS_Report (TRUE) ]
    String     ContentVer;
    [ SMS_Report (TRUE) ]
    UInt64     DeploymentFlags;
    [ SMS_Report (TRUE) ]
    String     ExcludeFileList;
    [ SMS_Report (TRUE) ]
    DateTime     LastReferenced;
    [ SMS_Report (TRUE) ]
    String     Location;
    [ SMS_Report (TRUE) ]
    String     PartialContentInfo;
    [ SMS_Report (TRUE) ]
    Boolean     PeerCaching;
    [ SMS_Report (TRUE) ]
    UInt32     PersistInCache;
    [ SMS_Report (TRUE) ]
    UInt32     ReferenceCount;
};
